const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("hsusa", {
    applicationName: "HSUSA TMS",
    version: "1.0.0",
    login: (username, password) => ipcRenderer.invoke("auth-login", { username, password }),
    logout: () => ipcRenderer.invoke("auth-logout"),
    getUserById: (userId) => ipcRenderer.invoke("users-get-by-id", userId),
    getUsers: () => ipcRenderer.invoke("users-get-all"),
    createUser: (user) => ipcRenderer.invoke("users-create", user),
    updateUser: (user) => ipcRenderer.invoke("users-update", user),
    deleteUser: (userId) => ipcRenderer.invoke("users-delete", userId),
    changeUserPassword: (request) => ipcRenderer.invoke("users-change-password", request),
    getRoles: () => ipcRenderer.invoke("roles-get-all"),
    getRoleById: (roleId) => ipcRenderer.invoke("roles-get-by-id", roleId),
    createRole: (role) => ipcRenderer.invoke("roles-create", role),
    updateRole: (role) => ipcRenderer.invoke("roles-update", role),
    deleteRole: (roleId) => ipcRenderer.invoke("roles-delete", roleId),
    getSubjects: () => ipcRenderer.invoke("subjects-get-all"),
    getSubjectById: (subjectId) => ipcRenderer.invoke("subjects-get-by-id", subjectId),
    createSubject: (subject) => ipcRenderer.invoke("subjects-create", subject),
    updateSubject: (subject) => ipcRenderer.invoke("subjects-update", subject),
    deleteSubject: (subjectId) => ipcRenderer.invoke("subjects-delete", subjectId),
    getQuestions: () => ipcRenderer.invoke("questions-get-all"),
    getQuestionById: (questionId) => ipcRenderer.invoke("questions-get-by-id", questionId),
    createQuestion: (question) => ipcRenderer.invoke("questions-create", question),
    updateQuestion: (question) => ipcRenderer.invoke("questions-update", question),
    deleteQuestion: (questionId) => ipcRenderer.invoke("questions-delete", questionId),
    deleteQuestions: (questionIds) => ipcRenderer.invoke("questions-delete-many", questionIds),
    importQuestions: (questions) => ipcRenderer.invoke("questions-import", questions),
    getQualifications: () => ipcRenderer.invoke("qualifications-get-all"),
    getQualificationById: (id) => ipcRenderer.invoke("qualifications-get-by-id", id),
    createQualification: (qualification) => ipcRenderer.invoke("qualifications-create", qualification),
    updateQualification: (qualification) => ipcRenderer.invoke("qualifications-update", qualification),
    deleteQualification: (id) => ipcRenderer.invoke("qualifications-delete", id),
    assignQualificationUser: (input) => ipcRenderer.invoke("qualifications-assign-user", input),
    unassignQualificationUser: (input) => ipcRenderer.invoke("qualifications-unassign-user", input)
});
